// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apbyafrovlcpqsexviru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwYnlhZnJvdmxjcHFzZXh2aXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMzU5NTgsImV4cCI6MjA1MzkxMTk1OH0.PgVfXMxm9afbvtoRyKj5JyGfMfaKht-RNl-FHia3apY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);